'use server';

/**
 * @fileOverview AI flow to generate a compelling professional summary based on user career stage and experience.
 *
 * - generateProfessionalSummary - A function that generates the professional summary.
 * - GenerateProfessionalSummaryInput - The input type for the generateProfessionalSummary function.
 * - GenerateProfessionalSummaryOutput - The return type for the generateProfessionalSummary function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateProfessionalSummaryInputSchema = z.object({
  careerStage: z
    .string()
    .describe('The career stage of the user (e.g., Entry-Level, Mid-Career, Senior-Level).'),
  experienceSummary: z
    .string()
    .describe('A summary of the user\'s work experience, skills, and achievements.'),
});
export type GenerateProfessionalSummaryInput = z.infer<typeof GenerateProfessionalSummaryInputSchema>;

const GenerateProfessionalSummaryOutputSchema = z.object({
  professionalSummary: z.string().describe('A compelling professional summary generated by the AI.'),
});
export type GenerateProfessionalSummaryOutput = z.infer<typeof GenerateProfessionalSummaryOutputSchema>;

export async function generateProfessionalSummary(
  input: GenerateProfessionalSummaryInput
): Promise<GenerateProfessionalSummaryOutput> {
  return generateProfessionalSummaryFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateProfessionalSummaryPrompt',
  input: {schema: GenerateProfessionalSummaryInputSchema},
  output: {schema: GenerateProfessionalSummaryOutputSchema},
  prompt: `You are a professional resume writer. Generate a compelling professional summary based on the user's career stage and experience. The summary should be concise, engaging, and tailored to capture the attention of recruiters and hiring managers.

Career Stage: {{{careerStage}}}
Experience Summary: {{{experienceSummary}}}

Professional Summary:`,
});

const generateProfessionalSummaryFlow = ai.defineFlow(
  {
    name: 'generateProfessionalSummaryFlow',
    inputSchema: GenerateProfessionalSummaryInputSchema,
    outputSchema: GenerateProfessionalSummaryOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
